### ISSUE TITLE
Separar CPF e CNPJ

### ISSUE THREAD

**Issue by hermesalvesbr** [Guiqft/directus-masked-input#2]
No cadastro da pessoa é só CPF, e é importante que além da máscara que teste se é válido.

No momento ele está misturando cpf, cnpj na quantidade de dígitos ele valida cpf ou cnpj. Seria possível separar? Pois não combina CNPJ no cadastro do indivíduo.

**Comment by Guiqft** [comment]
Agora CPF e CNPJ já são máscaras separadas :)
