### ISSUE TITLE
Erro no Directus 7.6.1

### ISSUE THREAD

**Issue by jrvidotti** [Guiqft/directus-masked-input#3]
Ao ativar um campo com máscara e tentar editar um registro, dá "Página não encontrada".

Log do console:

<img width="1177" alt="image" src="https://user-images.githubusercontent.com/5623041/160222930-19ccaa50-7a00-4a99-8e01-ccc3c755b2fa.png">

O que pode ser isso?

**Comment by jrvidotti** [comment]
Achei aqui esse erro no banco de dados (directus_fields).

<img width="535" alt="image" src="https://user-images.githubusercontent.com/5623041/160223242-792177ee-1150-4bf3-8cdd-6fe317675d22.png">

**Comment by Guiqft** [comment]
A extensão foi atualizada pra a última versão do Directus, v9.18.0
